# 4.2.4 오류를 숨기지 않음

어떤 때는 오류를 숨기고 아무 일도 없었던 것처럼 동작하도록 코드를 작성하고 싶을 수 있다.

오류를 숨기는 것은 아래와 같은 2가지 오류 모두에 문제를 일으킨다.

```java
1. 복구할 수 없는 오류 - 에러(error)
2. 복구할 수 있는 오류 - 예외(exception)
```

### 🎯 1. 복구할 수 없는 오류(에러)를 숨기는 경우
```java
public class Game {
    public void test() {
        try {
            ...
        } catch (StackOverflowError e) {}
    }   
}
```
코드 작성 시에 `StackOverflowError`가 발생하면,

프로그램이 중단되는 것을 멈추기 위해 오류를 try-catch로 잡아서 

내부 코드를 보기 전에는 프로그램 동작에 아무일도 없는 것처럼 숨겼다.

이렇게 되면, 내부 코드를 보기 전에는 개발팀이 오류를 알아차릴 수 없다.

따라서 버그가 꽤 오랫동안 알아차리지 못한 채 그대로 남아있을 수 있다.


### 🎯 2. 복구할 수 있는 오류(예외)를 숨기는 경우
```java
public class Number {
    
    private int number;
    
    public Number(int number) {
        validateNumber(number);
        this.number = number;
    }
    
    public void validateNumber(int number) {
        if (number > 10) {
            throw new IlleagalArgumentException("숫자는 10 미만으로 입력해주세요.");
        }
    }
}
```
```java
public class Game {
    
    private Number number;
    
    public Game(int readNumber) {
        try {
            number = new Number(readNumber);
        } catch (IlleagalArgumentException e) {
            number = new Number(0);
        }
    }
}
```
```java
public class Controller {
    
    private Game game = new Game(InputView.readNumber());
    
    ...
}
```
위의 코드에서 `Number`가 생성될 때 10 이상의 수가 들어오면 `IllegalArgumentException`을 반환하도록 의도했다.

하지만, `Game`에서 `Number` 생성 시에 예외가 발생하는 것을 숨기고 싶어서,

`Number`의 기본값의 수로 0을 생각하고 예외 발생 시 기본값 0으로 `Number`를 생성해서 지정해줬다.

`Game`을 사용하는 `Controller`에서는 아무일도 없는 것처럼 `Game`을 사용하게 되는 것이다.

이러한 상황은 결국 심각한 버그를 초래할 수 있다.

`Number`를 호출하는 `Game`에서 복구할 수 있는 오류를 숨기면,

오류로부터 복구할 수 있는 기회를 없애는 것이 된다.

---

## 🎯 오류가 발생했다는 사실을 숨길 수 있는 몇 가지 방법

다음은 오류가 발생했다는 사실을 숨기는 몇 가지 방법을 다룬다.

이러한 기술 중 일부는 특정 상황에서 유용하겠지만, 오류 처리에 있어서는 일반적으로 바람직하지 않다.

### ✅ 1. 기본값 반환

오류가 발생하고 함수가 원하는 값을 반환할 수 없는 경우 기본값을 반환하는 것이 

간단하고 쉬운 해결책인 것처럼 보일 수 있다.
```java
기본값 반환 VS 적절한 에러 전달과 처리를 위해 코드를 추가하는 것
```

둘을 비교해보면 후자가 더 많은 비용이 드는 것처럼 보인다.

하지만, **기본값 반환의 문제점은 오류가 발생했다는 사실을 숨긴다는 것이다!**

호출하는 쪽에서는 모든 것이 정상인 것처럼 계속 진행하게 되어 정상 상황으로 착각하게 된다.

### 🎯기본값 반환 예시
```java
public class RacingGame {
    private List<Car> cars;

    Position averagePosition() {
        final var average = cars.stream()
                .mapToInt(Car::position)
                .average()
                .orElse(-1); // 게임 참여자가 없다.

        return new Position(average);
    }
}
```
위의 경우에 cars를 돌면서 모든 차들의 position을 받아서 평균 값을 가져오는데,

만약 게임 참여자가 없다면 기본 값으로 '-1'을 지정하여 반환하는 코드를 작성했다.

하지만 이러한 기본값은 매직 넘버가 된다.

`averagePosition()`을 호출한 쪽에서 반환값으로 -1을 받는다면,

한눈에 무슨 의미인지 알아차리기 힘들 것이다.

이처럼 오류를 기본값으로 숨기지 않고, 

`orElseThrow`를 통해 "게임 참여자가 없습니다."라는 예외 메시지를 보여주는 것이 더 좋을 것이다.

코드에 기본값을 두는 것이 유용한 경우가 있을 수 있지만, 오류를 처리할 때는 대부분의 경우 적합하지 않다. 

잘못된 데이터로 시스템이 제대로 작동하지 않을 수 있으므로 **신속한 실패**와 **요란한 실패**를 위반하는 것이다.

<br>

### ✅ 2. 널 객체 패턴
널 객체는 개념적으로 기본값과 유사하지만 이것을 더 확장해서 더 복잡한 객체(클래스 등)를 다룬다.

널 객체는 실제 반환값처럼 보이지만 모든 멤버 함수는 아무것도 하지 않거나, 의미없는 기본값들을 반환한다.

널 객체 패턴은 빈 리스트 반환같은 간단한 것 부터 전체 클래스 구현과 같은 복잡한 것까지 다양할 수 있다.

여기서는 빈 리스트 반환 정도만 살펴보고, 자세한 패턴은 6장에서 다룬다.

### 🎯널 객체 패턴 예시
```java
public class CarController {
    
    public List<Car> getWinner() {
        try {
            List<Car> winners = racingCars.getWinners();
            return winners;
        } catch (IllegalArgumentException e) {
            return Collections.emptyList();
        }
    }
}
```
오류가 발생할 때 오류를 처리하지 않고 빈 리스트를 반환하는 것이다.

이는 기본값 반환과 비슷하게 `getWinner()`를 호출하는 쪽에서 정상적으로 처리되었다고 착각할 수 있다.

오류가 발생한 것이 아니라, 우승자가 없구나! 라고 생각할 수 있다.

<br>

### ✅ 3. 아무것도 하지 않음

코드가 무언가를 반환하지 않고 어떤 작업을 수행하는 경우, 오류가 발생했다는 신호를 보내지 않을 수 있다.

이것은 개발자가 가지고 있는 정신 모델(예측한 것)과 실제로 수행하는 것 사이의 불일치를 일으킬 수 있다.

### 🎯널 객체 패턴 예시

### 3-1. 오류 발생 시 아무것도 하지 않음
```java

public class RacingCar {
    
    private List<Car> cars;
    
    public void addCar(Car car) {
        if (car.getPosition() == 0) {
            return;
        }
        cars.add(car);
    }
}
```
위의 예시는 자동차의 리스트를 가지고, `addCar()`로 자동차를 추가하는 코드 예시이다.

이때, 추가할 car의 Position이 0이라면 저장하지 않기 위해서 `return`으로 추가되지 않고 끝난다.

### 3-2. 예외 억제
```java
public class Number {
    
    private int number;
    
    public Number(int number) {
        validateNumber(number);
        this.number = number;
    }
    
    public void validateNumber(int number) {
        if (number > 10) {
            throw new IlleagalArgumentException("숫자는 10 미만으로 입력해주세요.");
        }
    }
}
```
```java
public class Game {
    
    private Number number;
    
    public Game(int readNumber) {
        try {
            number = new Number(readNumber);
        } catch (IlleagalArgumentException e) { }
    }
}
```

위의 예시는 `Game` 생성 시 수를 입력받아서 생성하는데, 입력된 수가 10보다 크다면

`Number` 클래스에서 `IlleagalArgumentException`을 발생시킨다.

이때, `Game`에서 `IlleagalArgumentException`을 catch로 잡고 억제해서 아무런 일도 하지 않는다.

### 3-3. 예외 탐지 및 오류 기록
```java
public class Number {
    
    private int number;
    
    public Number(int number) {
        validateNumber(number);
        this.number = number;
    }
    
    public void validateNumber(int number) {
        if (number > 10) {
            throw new IlleagalArgumentException("숫자는 10 미만으로 입력해주세요.");
        }
    }
}
```
```java
public class Game {
    
    private Number number;
    
    public Game(int readNumber) {
        try {
            number = new Number(readNumber);
        } catch (IlleagalArgumentException e) {
            logger.logError(e); // IlleagalArgumentException이 기록된다.
        }
    }
}
```
이는 3-2의 예외 억제에서 약간 개선된 것이긴 하지만 여전히 바람직하지 않다.

예외가 발생하면 catch로 잡고, 호출하는 쪽에 실패 신호를 보내지 않는다.

대신 잡은 `IlleagalArgumentException`을 로그에 남겨 개발자가 로그를 봤을 때 오류가 발생했음을 알 수 있게 한다.

<br>

세 가지 `오류 시 아무것도 하지 않음` 예시에서 공통적인 문제는

호출하는 쪽에서 오류가 발생했음을 인지하지 못하고, 정상 상황으로 판단하여 소프트웨어에 버그가 일어날 가능성이 많다는 것이다.

견고함을 위해 오류를 당장 숨겼다가, 실제로 더 심각한 결과를 초래할 수 있을 것이다.

오류를 발생하면 알리는 것이 좋고, 4.3절에서 오류 발생 시 알리는 법을 설명한다.
