# 4.3.7 암시적 방법: 프로미스 또는 퓨처

> 이 부분은 자바스크립트와 깊은 관련이 있는 내용 같습니다.<br>
> 최대한 자바와 연관지어 설명하고자 찾아봤지만 모두 자바스크립트 관련된 내용만 나오고, 아직은 당장 알아두면 좋은 내용이 아니기에 간단히 보고 넘어가면 될 듯 합니다.

비동기적으로 실행하는 코드를 작성할 때 **프로미스**나 **퓨처**를 **반환**하는 함수를 작성하는 것이 일반적이다.<br>
많은 언어에서 프로미스나 퓨처는 **오류 상태도 전달할 수 있다**.

프로미스나 퓨처를 사용할 때 일반적으로 오류 처리가 강제되는 것은 아니고, 해당 함수에 대한 코드 계약의 세부 조항을 알지 못하면 오류 처리를 해줘야 한다는 것을 모를 수 있다.<br>
따라서 프로미스 또는 퓨처는 **암시적 방법**이다.

```javascript
class NegativeNumberError extends Error {
}

Promise<Double> getSquareRoot(Double value) async { // async는 비동기 함수임을 표시
    await Timer.wait(Duration.ofSeconds(1)); // 실제 동작 전, 1초를 기다린다.

    if (value < 0.0) {
        throw new NegativeNumberError(value); // 오류 발생. 프로미스 거부
    }
    return Math.sqrt(value); // 값 반환. 프로미스 이행
}
```

함수 안에서 오류가 발생하면 **프로미스는 거부**되고, 올바르게 수행되면 **프로미스는 반환값과 함께 이행**된다.

이제 `getSquareRoot()`를 호출하는 코드를 보자.

```javascript
void displayResult() {
    getSquareRoot(inputView.getInputNumber())
        .then(squareRoot -> outputView.printResult("Result : " + squareRoot))
        .catch(error -> outputView.printError("Error : " + error.toString()));
}
```

결과가 올바르게 **이행** 됐다면 `then()`이, 그렇지 않다면 `catch()` 구문이 실행된다.<br>
`then()`은 프로미스가 이행되면 호출되는 콜백 기능을 설정하기 위해, `catch()`는 프로미스가 거부되면 호출되는 콜백을 설정하기 위해 사용된다.

## 왜 프로미스는 암묵적 오류 전달 기법인가?

오류가 발생하고 프로미스가 거부될 수 있음을 호출자에게 알리려면, 프로미스를 생성하는 함수의 세부 조항이나 구현 세부 사항을 직접 확인해야한다.

## 프로미스 명시적으로 만들기

4.3.5절에 나온 `Result` 반환 유형을 사용한다.

```javascript
Promise<Result<Double, NegativeNumberError>> getSquareRoot(Double value) async {
    await Timer.wait(Duration.ofSeconds(1));

    if (value < 0.0) {
        return Result.ofError(new NegativeNumberError(value));
    }
    return Result.ofValue(Math.sqrt(value));
}
```

하지만, 이 방법은 코드가 복잡해지기에 흔히 쓰이는 방법은 아니다.
